name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: jdk

      - name: Download JavaFX SDK
        run: |
          wget https://gluonhq.com/download/javafx-17-sdk-linux/ -O javafx-sdk.zip
          unzip javafx-sdk.zip -d javafx-sdk
          echo "JAVA_FX_HOME=$GITHUB_WORKSPACE/javafx-sdk" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Code Quality Check
        run: ./gradlew check

      - name: Build Release
        run: ./gradlew jfxJar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: javafx-application
          path: build/libs/*.jar

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
