name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: jdk

      - name: Download JavaFX SDK
        run: |          
          wget https://download2.gluonhq.com/openjfx/21.0.1/openjfx-21.0.1_linux-x64_bin-sdk.zip -O javafx-sdk.zip
          unzip javafx-sdk.zip -d javafx-sdk
          echo "JAVA_FX_HOME=$GITHUB_WORKSPACE/javafx-sdk" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Code Quality Check
        run: ./gradlew check

      - name: Build Release
        run: ./gradlew jar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: javafx-application
          path: build/libs/*.jar
      - name: Create release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
        run: |
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                --generate-notes
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: v1.0.0
#          release_name: Release v1.0.0
#          draft: true
#          prerelease: true
